/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConteudosRouteImport } from './routes/_authenticated/conteudos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedQuestoesRouteImport } from './routes/_authenticated/questoes'
import { Route as AuthenticatedRevisoesRouteImport } from './routes/_authenticated/revisoes'
import { Route as AuthenticatedSessoesRouteImport } from './routes/_authenticated/sessoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConteudosRoute = AuthenticatedConteudosRouteImport.update({
  id: '/_authenticated/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/_authenticated/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/_authenticated/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuestoesRoute = AuthenticatedQuestoesRouteImport.update({
  id: '/_authenticated/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRevisoesRoute = AuthenticatedRevisoesRouteImport.update({
  id: '/_authenticated/revisoes',
  path: '/revisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessoesRoute = AuthenticatedSessoesRouteImport.update({
  id: '/_authenticated/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/sessoes': typeof AuthenticatedSessoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/revisoes': typeof AuthenticatedRevisoesRoute
  '/sessoes': typeof AuthenticatedSessoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conteudos': typeof AuthenticatedConteudosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/questoes': typeof AuthenticatedQuestoesRoute
  '/_authenticated/revisoes': typeof AuthenticatedRevisoesRoute
  '/_authenticated/sessoes': typeof AuthenticatedSessoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/reset-password'
    | '/configuracoes'
    | '/conteudos'
    | '/metas'
    | '/planner'
    | '/questoes'
    | '/revisoes'
    | '/sessoes'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/configuracoes'
    | '/conteudos'
    | '/metas'
    | '/planner'
    | '/questoes'
    | '/revisoes'
    | '/sessoes'
    | '/'
  id:
    | '__root__'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conteudos'
    | '/_authenticated/metas'
    | '/_authenticated/planner'
    | '/_authenticated/questoes'
    | '/_authenticated/revisoes'
    | '/_authenticated/sessoes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConteudosRoute: typeof AuthenticatedConteudosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedQuestoesRoute: typeof AuthenticatedQuestoesRoute
  AuthenticatedRevisoesRoute: typeof AuthenticatedRevisoesRoute
  AuthenticatedSessoesRoute: typeof AuthenticatedSessoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conteudos': {
      id: '/_authenticated/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof AuthenticatedConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/questoes': {
      id: '/_authenticated/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof AuthenticatedQuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revisoes': {
      id: '/_authenticated/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof AuthenticatedRevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessoes': {
      id: '/_authenticated/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof AuthenticatedSessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConteudosRoute: AuthenticatedConteudosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedQuestoesRoute: AuthenticatedQuestoesRoute,
  AuthenticatedRevisoesRoute: AuthenticatedRevisoesRoute,
  AuthenticatedSessoesRoute: AuthenticatedSessoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
